// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// iter
Rcpp::List iter(int max_iter, float tol, arma::mat VD, arma::mat VD2, arma::mat V, arma::mat B, double alpha, double beta, double nu, double kappa);
RcppExport SEXP _spcaRcpp_iter(SEXP max_iterSEXP, SEXP tolSEXP, SEXP VDSEXP, SEXP VD2SEXP, SEXP VSEXP, SEXP BSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP nuSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< float >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type VD(VDSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type VD2(VD2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    rcpp_result_gen = Rcpp::wrap(iter(max_iter, tol, VD, VD2, V, B, alpha, beta, nu, kappa));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spcaRcpp_iter", (DL_FUNC) &_spcaRcpp_iter, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_spcaRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
