# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iter <- function(max_iter, tol, VD, VD2, V, B, alpha, beta, nu, kappa) {
    .Call('_spcaRcpp_iter', PACKAGE = 'spcaRcpp', max_iter, tol, VD, VD2, V, B, alpha, beta, nu, kappa)
}

